UserStory #281 - create login page
ita-social-projects/BeautyProjectFront pull request #7
Opened 2022-06-23 19:48 UTC by shv833

2022-06-23 19:55 UTC, OleksiiDatsiuk approved these changes
Looks good :)

2022-06-27 10:55 UTC, pazuzu-ua approved these changes

2022-06-27 11:33 UTC, Misha86 approved these changes

2022-06-27 11:33 UTC, Misha86 commented on src/components/login_page/login_page.js
> +                url: "http://3.65.253.196/auth/jwt/create/",
Does it possible to get a host from a response or from a browser?

2022-06-28 12:35 UTC, pazuzu-ua requested changes

2022-06-28 12:35 UTC, pazuzu-ua commented on src/components/login_page/login_page.js
> +                url: "http://3.65.253.196/auth/jwt/create/",
Please, change to "https://g6bcybbjx1.execute-api.eu-central-1.amazonaws.com/auth/jwt/create/"

2022-07-08 12:45 UTC, OleksiiDatsiuk approved these changes

2022-07-08 12:46 UTC, merged